adding the cross browser testing blog post
getgauge/gauge.org pull request #189
Opened 2020-09-11 03:28 UTC by sguptatw

2020-09-15 10:56 UTC, NivedhaSenthil approved these changes

2020-09-15 12:35 UTC, zabil commented
@sguptatw can you update the image?

2020-09-17 15:31 UTC, zabil requested changes
Some of the changes you can apply directly by clicking the "commit" this change button. However other changes like changes to whole paragraphs and deleting paragraphs you need to make locally.

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +define criteria where the system will be used.
```suggestion
defines where the application will be used.
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +(NFR). Cross browser requirements do not define the system's behavior but
```suggestion
(NFR). Cross browser requirements do not define the application's behavior but 
```

Changing system to application as it's more relevant. The wikipedia usage of system is more generic when we we talk about browsers we can use application.

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +the cross browser issues.
Change this whole para to

In my experience as a developer and tester, I've seen a lot of teams hoping to uncover cross browser issues
by only running their automated UI tests across browsers.

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +I feel there’s a better and faster way to check cross browser issues than
```suggestion
I feel there’s a better and faster way to verify cross browser compatibility.
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +alternatives to address them.
Change whole paragraph to

Not all cross browser compatibility issues are caught by functional tests. 
In this post we look at ways to ensure cross browser compatibility without 
relying on functional tests.

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +relying only on functional tests.
Remove this line

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +From the definition of BDD or Behaviour Driven Development, we know that,
Remove this line

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +rendering works.
Change this whole paragraph to

There are three main components to how a browser renders a web page.

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +The functionality of any software does not change with the browser in which it
```suggestion
The functionality of the application does is the same across browsers.
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +is executing. To ensure that the software functions as expected in the browser/s
```suggestion
To ensure that the application works as expected in the browser/s 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +one has to ensure that the CSS,HTML and the features of the scripting language
```suggestion
you have to ensure that the CSS, HTML and JavaScript 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +used works in the respective browsers.
```suggestion
works across browsers. 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +
Change the whole para to

This can be done by static analysis of front end code without running the application.

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +Static code analysis helps reduce visual regression defects. [CanIUse](https://caniuse.com/)
```suggestion
Static code analysis reduces visual regression defects. [CanIUse](https://caniuse.com/) 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +supported by a relevant browser!
```suggestion
supported by a relevant browser.
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +To get that kind of pointed feedback, plugins like
```suggestion
To get that specific feedback, plugins like 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +### JavaScript Checking with esLint against caniuse db
```suggestion
### Checking JavaScript with esLint against caniuse db
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +They allow configuration of target browser/s, percentage of feature supported.
Can you please explain `They`?

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +Javascript wasn't a standard across browsers like IE and Firefox. We find
```suggestion
In the early days, JavaScript features weren't standardised across browsers like IE and Firefox. We find 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +recent times browsers are being standardized. [Polyfills](https://polyfill.io/v3/),
```suggestion
recent times browsers follow standards. [Polyfills](https://polyfill.io/v3/), 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +browsers are supported.
```suggestion
browser versions need to be supported. 
```

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +frameworks will eventually benefit the business.
Delete this paragraph

2020-09-17 15:31 UTC, zabil commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +[browsers lacked standards](https://en.wikipedia.org/wiki/Browser_wars).
Delete this paragraph

2020-09-17 16:20 UTC, sguptatw commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +[browsers lacked standards](https://en.wikipedia.org/wiki/Browser_wars).
done

2020-09-17 16:20 UTC, sguptatw commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +frameworks will eventually benefit the business.
done

2020-09-17 16:20 UTC, sguptatw commented on source/posts/2020-09-10-cross-browser-testing-with-non-functional-tests.html.markdown.erb
> +the cross browser issues.
done

2020-09-18 13:14 UTC, zabil approved these changes

2020-09-18 13:14 UTC, merged