Blog post Test Automation with Limited Resources
getgauge/gauge.org pull request #194
Opened 2024-02-27 09:26 UTC by derdualist

2024-02-27 09:35 UTC, sriv requested changes

2024-02-27 09:35 UTC, sriv commented on source/posts/2024-02-26-test-automation-with-limited-resources.html.markdown.erb
> +Leave a comment below to let us know what you think about this approach.
the gauge blog site does not have a commenting mechanism currently.

2024-02-27 09:35 UTC, sriv commented
Thank you for the blog @derdualist . The preview of your post lies here: https://deploy-preview-194--kind-hugle-dbff4b.netlify.app/2024/02/26/test-automation-with-limited-resources/

Please see if this matches your expectation.

2024-02-28 12:40 UTC, derdualist commented
Everything seems fine now. Thanks for the review.

2024-02-28 13:08 UTC, sriv approved these changes

2024-02-28 13:09 UTC, merged

2024-02-28 13:17 UTC, sriv commented
Thank you @derdualist . The post is live now - https://gauge.org/2024/02/26/test-automation-with-limited-resources/

2024-02-28 13:19 UTC, sriv commented
My apologies on the commenting. I see that there is discus enabled. ( My laptop browser had a blocker which disabled it).

If you wish to add the last line back I will merge it.

Sorry again for the mixup.

2024-02-28 14:16 UTC, derdualist commented
Ah ok, merging the last line back in would be nice. 
No worries. I appreciate we could leave a posting, thanks a lot!